from __future__ import annotations

from typing import Optional, Dict, Any, List
from app.cpn.schemas import (
    CpnProductInput,
    CpnCurveResponse,
    CpnCurvePoint,
    CpnBreakpoints,
    CPN_RISK_NOTES,
)
from app.cpn.payoff import calculate_cpn_payoff_core


def generate_cpn_curve(product: CpnProductInput) -> CpnCurveResponse:
    """
    Generate payoff curve points from underlying return -50% to +60% in steps of 1%.
    Every single point is generated by calling calculate_cpn_payoff_core.
    """
    points: List[CpnCurvePoint] = []
    
    # x = underlying return % from -50 to +60 in steps of 1
    for shock in range(-50, 61):
        r_dec = shock / 100.0
        res = calculate_cpn_payoff_core(
            investment=product.investment,
            tenor_years=product.tenor_years,
            protection_pct=product.protection_pct,
            participation_pct=product.participation_pct,
            r=r_dec,
            cap_pct=product.cap_pct,
            coupon_pct_pa=product.coupon_pct_pa,
        )
        points.append(
            CpnCurvePoint(
                underlying_return_pct=float(shock),
                investor_return_pct=res["return_pct"],
                final_amount=res["final_amount"],
            )
        )

    # Calculate exact breakpoints
    # 1. Floor return (at r <= 0)
    floor_res = calculate_cpn_payoff_core(
        investment=product.investment,
        tenor_years=product.tenor_years,
        protection_pct=product.protection_pct,
        participation_pct=product.participation_pct,
        r=0.0,
        cap_pct=product.cap_pct,
        coupon_pct_pa=product.coupon_pct_pa,
    )
    floor_return_pct = floor_res["return_pct"]

    # 2. Cap breakpoints
    cap_underlying_return_pct: Optional[float] = None
    cap_return_pct: Optional[float] = None
    if product.cap_pct is not None:
        cap_underlying_return_pct = float(product.cap_pct)
        cap_res = calculate_cpn_payoff_core(
            investment=product.investment,
            tenor_years=product.tenor_years,
            protection_pct=product.protection_pct,
            participation_pct=product.participation_pct,
            r=product.cap_pct / 100.0,
            cap_pct=product.cap_pct,
            coupon_pct_pa=product.coupon_pct_pa,
        )
        cap_return_pct = cap_res["return_pct"]

    # 3. Break-even: smallest underlying return % where investor return_pct >= 0
    # If floor_return_pct >= 0, investor never has a nominal loss -> null
    break_even_underlying_return_pct: Optional[float] = None
    if floor_return_pct < 0:
        deficit_pct = -floor_return_pct
        needed_r_pct = (deficit_pct / product.participation_pct) * 100.0
        if product.cap_pct is None or needed_r_pct <= product.cap_pct:
            break_even_underlying_return_pct = round(needed_r_pct, 4)

    breakpoints = CpnBreakpoints(
        floor_return_pct=floor_return_pct,
        cap_underlying_return_pct=cap_underlying_return_pct,
        cap_return_pct=cap_return_pct,
        break_even_underlying_return_pct=break_even_underlying_return_pct,
    )

    return CpnCurveResponse(
        points=points,
        breakpoints=breakpoints,
        risk_notes=CPN_RISK_NOTES,
    )
